
import React, { useState } from 'react';
import {
  Building2,
  Users,
  TrendingUp,
  Plus,
  ArrowLeftRight,
  MapPin,
  Phone,
  Calendar as CalendarIcon,
  MoreHorizontal,
  Download,
  BarChart3,
  PieChart,
  LineChart,
  Search,
  CheckCircle2,
  AlertCircle,
  X,
  ChevronRight,
  UserPlus,
  AlertTriangle
} from 'lucide-react';
import { cn } from '@/lib/utils';
import { moveToPage } from '@/internal';

import AppLayout from '@/components/AppLayout';
import PageHeader from '@/components/PageHeader';
import TabNav from '@/components/TabNav';
import StatCard from '@/components/StatCard';
import DataTable from '@/components/DataTable';
import StatusBadge from '@/components/StatusBadge';
import SearchFilter from '@/components/SearchFilter';
import FormSection from '@/components/FormSection';
import ConfirmDialog from '@/components/ConfirmDialog';

// --- Mock 존재 코드 목록 (중복 체크용) ---
const EXISTING_CODES = ['SG-001', 'SG-002', 'SG-003', 'SG-004'];

// --- 지점 등록 폼 타입 ---
interface BranchForm {
  name: string;
  code: string;
  phone: string;
  address: string;
  addressDetail: string;
  managerId: string;
  openTime: string;
  closeTime: string;
  memo: string;
}

interface FormErrors {
  name?: string;
  code?: string;
  phone?: string;
  address?: string;
  managerId?: string;
}

const EMPTY_FORM: BranchForm = {
  name: '',
  code: '',
  phone: '',
  address: '',
  addressDetail: '',
  managerId: '',
  openTime: '06:00',
  closeTime: '23:30',
  memo: '',
};

// 전화번호 포맷 검증
const isValidPhone = (v: string) => /^(0\d{1,2})-(\d{3,4})-(\d{4})$/.test(v);

// 지점 코드 검증: 영문 2~5자
const isValidCode = (v: string) => /^[A-Z]{2,5}$/.test(v);

// 지점명 검증: 2~30자
const isValidName = (v: string) => v.trim().length >= 2 && v.trim().length <= 30;

export default function BranchManagement() {
  const [activeTab, setActiveTab] = useState('list');
  const [isAddBranchOpen, setIsAddBranchOpen] = useState(false);
  const [isMoveMemberOpen, setIsMoveMemberOpen] = useState(false);

  // 비활성화 관련 상태
  const [deactivateTarget, setDeactivateTarget] = useState<any>(null);
  const [deactivateStep, setDeactivateStep] = useState<1 | 2>(1); // 1: 영향 범위 확인, 2: 2차 확인
  const [isDeactivateOpen, setIsDeactivateOpen] = useState(false);

  // 지점 등록 폼 상태
  const [branchForm, setBranchForm] = useState<BranchForm>(EMPTY_FORM);
  const [formErrors, setFormErrors] = useState<FormErrors>({});
  const [codeAutoGenerated, setCodeAutoGenerated] = useState(false);

  // --- Mock Data ---
  const branches = [
    { id: 1, name: '스포짐 종각점', code: 'SG-001', address: '서울 종로구 종로 33', phone: '02-123-4567', members: 1250, staffs: 15, activeContracts: 87, status: 'active', regDate: '2024-01-10' },
    { id: 2, name: '스포짐 강남점', code: 'SG-002', address: '서울 강남구 테헤란로 123', phone: '02-987-6543', members: 1840, staffs: 22, activeContracts: 134, status: 'active', regDate: '2024-02-15' },
    { id: 3, name: '스포짐 여의도점', code: 'SG-003', address: '서울 영등포구 국제금융로 10', phone: '02-555-7777', members: 920, staffs: 12, activeContracts: 61, status: 'active', regDate: '2024-05-20' },
    { id: 4, name: '스포짐 잠실점 (준비중)', code: 'SG-004', address: '서울 송파구 올림픽로 300', phone: '02-111-2222', members: 0, staffs: 5, activeContracts: 0, status: 'inactive', regDate: '2025-01-01' },
  ];

  const movementHistory = [
    { id: 1, memberName: '홍길동', from: '종각점', to: '강남점', date: '2026-02-10', processor: '김관리' },
    { id: 2, memberName: '이영희', from: '강남점', to: '여의도점', date: '2026-02-12', processor: '이팀장' },
    { id: 3, memberName: '박철수', from: '여의도점', to: '종각점', date: '2026-02-15', processor: '최점장' },
  ];

  const integratedStats = [
    { branch: '종각점', members: 1250, sales: '45,000,000', attendance: '78%' },
    { branch: '강남점', members: 1840, sales: '72,000,000', attendance: '82%' },
    { branch: '여의도점', members: 920, sales: '38,000,000', attendance: '75%' },
    { branch: '잠실점', members: 0, sales: '0', attendance: '0%' },
  ];

  // --- 폼 검증 ---
  const validateForm = (): boolean => {
    const errors: FormErrors = {};

    if (!isValidName(branchForm.name)) {
      errors.name = '지점명은 2~30자로 입력해주세요.';
    }
    if (!branchForm.code.trim()) {
      errors.code = '지점 코드를 입력해주세요.';
    } else if (!isValidCode(branchForm.code)) {
      errors.code = '지점 코드는 영문 대문자 2~5자여야 합니다. (예: SGJ)';
    } else if (EXISTING_CODES.includes(branchForm.code)) {
      errors.code = '이미 사용 중인 지점 코드입니다.';
    }
    if (!branchForm.phone.trim()) {
      errors.phone = '연락처를 입력해주세요.';
    } else if (!isValidPhone(branchForm.phone)) {
      errors.phone = '올바른 전화번호 형식으로 입력해주세요. (예: 02-000-0000)';
    }
    if (!branchForm.address.trim()) {
      errors.address = '주소를 입력해주세요.';
    }
    if (!branchForm.managerId) {
      errors.managerId = '지점 관리자를 선택해주세요.';
    }

    setFormErrors(errors);
    return Object.keys(errors).length === 0;
  };

  const handleAutoGenerateCode = () => {
    // Mock: 다음 코드 자동 생성
    const nextNum = String(EXISTING_CODES.length + 1).padStart(3, '0');
    const generated = `SG${nextNum}`;
    setBranchForm(f => ({ ...f, code: generated }));
    setCodeAutoGenerated(true);
    // 코드 에러 초기화
    setFormErrors(prev => ({ ...prev, code: undefined }));
  };

  const handleFormChange = (field: keyof BranchForm, value: string) => {
    setBranchForm(f => ({ ...f, [field]: value }));
    // 해당 필드 에러 초기화
    if (field in formErrors) {
      setFormErrors(prev => ({ ...prev, [field]: undefined }));
    }
    if (field === 'code') setCodeAutoGenerated(false);
  };

  const handleAddBranchSubmit = () => {
    if (!validateForm()) return;
    // Mock 저장 성공
    alert(`지점 "${branchForm.name}"이(가) 등록되었습니다.`);
    setIsAddBranchOpen(false);
    setBranchForm(EMPTY_FORM);
    setFormErrors({});
  };

  const handleCloseAddBranch = () => {
    setIsAddBranchOpen(false);
    setBranchForm(EMPTY_FORM);
    setFormErrors({});
    setCodeAutoGenerated(false);
  };

  // --- 비활성화 처리 ---
  const openDeactivate = (row: any) => {
    setDeactivateTarget(row);
    setDeactivateStep(1);
    setIsDeactivateOpen(true);
  };

  const handleDeactivateConfirm = () => {
    if (deactivateStep === 1) {
      setDeactivateStep(2);
    } else {
      alert(`"${deactivateTarget?.name}" 지점이 비활성화되었습니다.`);
      setIsDeactivateOpen(false);
      setDeactivateTarget(null);
    }
  };

  // --- Handlers ---
  const handleMoveMember = () => setIsMoveMemberOpen(true);

  // --- Table Columns ---
  const branchColumns = [
    { key: 'id', header: 'No', width: 60, align: 'center' as const },
    { key: 'name', header: '지점명', sortable: true },
    { key: 'code', header: '지점 코드', width: 120 },
    { key: 'address', header: '주소' },
    { key: 'phone', header: '연락처', width: 140 },
    { key: 'members', header: '회원 수', width: 100, align: 'right' as const, render: (v: number) => v.toLocaleString() },
    { key: 'staffs', header: '직원 수', width: 100, align: 'right' as const },
    {
      key: 'status',
      header: '상태',
      width: 120,
      align: 'center' as const,
      render: (v: string) => (
        <StatusBadge variant={v === 'active' ? 'success' : v === 'inactive' ? 'warning' : 'default'} dot={true} label={v === 'active' ? '운영중' : v === 'inactive' ? '임시휴업' : '폐점'}/>
      )
    },
    { key: 'regDate', header: '등록일', width: 120 },
    {
      key: 'actions',
      header: '메뉴',
      width: 150,
      align: 'center' as const,
      render: (_: any, row: any) => (
        <div className="flex items-center gap-xs" >
          <button
            className="text-content-secondary hover:text-primary p-xs" onClick={() => {
              alert(`${row.name} 관리 모드로 전환합니다.`);
              moveToPage(966);
            }}>
            관리
          </button>
          <div className="w-[1px] h-3 bg-line" />
          <button className="text-content-secondary hover:text-primary p-xs" >수정</button>
          <div className="w-[1px] h-3 bg-line" />
          <button
            className="text-content-secondary hover:text-state-error p-xs"
            onClick={() => openDeactivate(row)}
          >
            비활성
          </button>
        </div>
      )
    }
  ];

  const historyColumns = [
    {
      key: 'memberName',
      header: '회원명',
      sortable: true,
      render: (v: string, row: any) => (
        <button
          className="text-primary hover:underline font-medium" onClick={() => moveToPage(985)}>
          {v}
        </button>
      )
    },
    { key: 'from', header: '원 지점' },
    { key: 'to', header: '이동 지점' },
    { key: 'date', header: '이동일', sortable: true },
    { key: 'processor', header: '처리자' },
  ];

  const integratedColumns = [
    { key: 'branch', header: '지점명' },
    { key: 'members', header: '회원 수', align: 'right' as const, render: (v: number) => v.toLocaleString() },
    { key: 'sales', header: '매출액 (원)', align: 'right' as const },
    { key: 'attendance', header: '평균 출석률', align: 'right' as const },
  ];

  return (
    <AppLayout >
      <PageHeader title="지점 관리 (멀티지점)" description="전체 지점의 운영 현황을 통합 관리하고 지점 간 데이터 이동을 처리합니다." actions={
          <div className="flex gap-sm">
            <button
              className="flex items-center gap-xs px-md py-sm bg-primary-light text-primary hover:bg-primary hover:text-white transition-all rounded-button text-Label font-semibold"
              onClick={handleMoveMember}
            >
              <ArrowLeftRight size={16} />
              지점 이동 신청
            </button>
            <button
              className="flex items-center gap-xs px-md py-sm bg-primary text-white hover:opacity-90 transition-all rounded-button text-Label font-semibold"
              onClick={() => setIsAddBranchOpen(true)}
            >
              <Plus size={16} />
              신규 지점 등록
            </button>
          </div>
        }/>

      <TabNav
        className="mb-lg" tabs={[
          { key: 'list', label: '지점 목록', icon: Building2 },
          { key: 'integrated', label: '통합 현황', icon: BarChart3 },
          { key: 'history', label: '지점 간 이동', icon: ArrowLeftRight },
        ]} activeTab={activeTab} onTabChange={setActiveTab}/>

      {/* --- TAB: 지점 목록 --- */}
      {activeTab === 'list' && (
        <div className="space-y-lg animate-in fade-in duration-300" >
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-md" >
            <StatCard label="총 지점 수" value="4개" icon={<Building2 />} variant="default"/>
            <StatCard label="총 회원 수" value="4,010명" icon={<Users />} change={{ value: 5.2, label: '지난달 대비' }} variant="mint"/>
            <StatCard label="이번 달 매출" value="1.55억" icon={<TrendingUp />} change={{ value: 12, label: '지난달 대비' }} variant="peach"/>
            <StatCard label="활성 지점" value="3개" icon={<CheckCircle2 />} description="1개 지점 준비 중" variant="default"/>
          </div>

          <SearchFilter searchPlaceholder="지점명 또는 주소 검색" filters={[
              {
                key: 'status',
                label: '상태',
                type: 'select',
                options: [
                  { value: 'active', label: '운영중' },
                  { value: 'inactive', label: '임시휴업' },
                  { value: 'closed', label: '폐점' }
                ]
              }
            ]}/>

          <DataTable title="지점 현황 목록" columns={branchColumns} data={branches} onDownloadExcel={() => alert('Excel 다운로드를 시작합니다.')}/>
        </div>
      )}

      {/* --- TAB: 통합 현황 --- */}
      {activeTab === 'integrated' && (
        <div className="space-y-lg animate-in fade-in duration-300" >
          <div className="flex justify-between items-center" >
            <div className="flex items-center gap-sm p-sm bg-surface rounded-xl border border-line shadow-card" >
              <button className="px-md py-xs bg-primary-light text-primary rounded-button text-Label font-semibold" >월간</button>
              <button className="px-md py-xs text-content-secondary hover:text-content rounded-button text-Label" >주간</button>
              <button className="px-md py-xs text-content-secondary hover:text-content rounded-button text-Label" >연간</button>
            </div>
            <p className="text-sm text-content-secondary" >기준: 2026.02.01 ~ 2026.02.19</p>
          </div>

          <div className="grid grid-cols-1 lg:grid-cols-3 gap-md" >
            <div className="lg:col-span-2 p-lg bg-surface rounded-xl border border-line shadow-card" >
              <div className="flex items-center justify-between mb-lg" >
                <h3 className="text-xl font-bold text-content flex items-center gap-xs" >
                  <BarChart3 className="text-primary" size={20}/>
                  지점별 매출 비교
                </h3>
              </div>
              <div className="space-y-lg" >
                {integratedStats.map((item, idx) => (
                  <div className="space-y-xs" key={idx}>
                    <div className="flex justify-between text-sm" >
                      <span className="font-medium text-content" >{item.branch}</span>
                      <span className="text-content-secondary" >{item.sales}원</span>
                    </div>
                    <div className="h-2 w-full bg-surface-secondary rounded-full overflow-hidden" >
                      <div
                        className="h-full bg-primary rounded-full" style={{ width: `${(parseInt(item.sales.replace(/,/g, '')) / 80000000) * 100}%` }}/>
                    </div>
                  </div>
                ))}
              </div>
            </div>

            <div className="p-lg bg-surface rounded-xl border border-line shadow-card" >
              <h3 className="text-xl font-bold text-content flex items-center gap-xs mb-lg" >
                <PieChart className="text-accent" size={20}/>
                지점별 회원 현황
              </h3>
              <div className="flex flex-col items-center justify-center h-[240px]" >
                <div className="relative w-40 h-40 rounded-full border-[12px] border-surface-secondary flex items-center justify-center" >
                  <div className="absolute inset-[-12px] rounded-full border-[12px] border-primary border-r-transparent border-b-transparent border-l-transparent rotate-[45deg]" />
                  <div className="absolute inset-[-12px] rounded-full border-[12px] border-accent border-t-transparent border-b-transparent border-l-transparent rotate-[-30deg]" />
                  <div className="text-center" >
                    <p className="text-Label text-content-secondary" >전체 회원</p>
                    <p className="text-xl font-bold font-bold text-content" >4,010</p>
                  </div>
                </div>
                <div className="mt-lg grid grid-cols-2 gap-sm w-full" >
                  <div className="flex items-center gap-xs" >
                    <div className="w-2 h-2 rounded-full bg-primary" />
                    <span className="text-Label text-content-secondary" >강남점 (46%)</span>
                  </div>
                  <div className="flex items-center gap-xs" >
                    <div className="w-2 h-2 rounded-full bg-accent" />
                    <span className="text-Label text-content-secondary" >종각점 (31%)</span>
                  </div>
                  <div className="flex items-center gap-xs" >
                    <div className="w-2 h-2 rounded-full bg-information" />
                    <span className="text-Label text-content-secondary" >여의도점 (23%)</span>
                  </div>
                </div>
              </div>
            </div>
          </div>

          <DataTable title="지점별 상세 통합 통계" columns={integratedColumns} data={integratedStats} onDownloadExcel={() => alert('Excel 다운로드')}/>
        </div>
      )}

      {/* --- TAB: 지점 간 이동 --- */}
      {activeTab === 'history' && (
        <div className="space-y-lg animate-in fade-in duration-300" >
          <div className="grid grid-cols-1 md:grid-cols-3 gap-md" >
            <StatCard label="이달의 지점 이동" value="12건" icon={<ArrowLeftRight />} variant="default"/>
            <StatCard label="주요 유입 지점" value="강남점" icon={<UserPlus />} description="최근 30일 기준" variant="mint"/>
            <StatCard label="주요 유출 지점" value="여의도점" icon={<X size={24} />} description="거주지 이전 사유 80%" variant="default"/>
          </div>

          <SearchFilter searchPlaceholder="회원명 검색" filters={[
              {
                key: 'dateRange',
                label: '조회 기간',
                type: 'dateRange'
              },
              {
                key: 'fromBranch',
                label: '출발 지점',
                type: 'select',
                options: branches.map(b => ({ value: b.name, label: b.name }))
              }
            ]}/>

          <DataTable title="회원 지점 이동 이력" columns={historyColumns} data={movementHistory}/>
        </div>
      )}

      {/* --- MODAL: 신규 지점 등록 (검증 포함) --- */}
      {isAddBranchOpen && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 backdrop-blur-sm p-md" >
          <div className="w-full max-w-2xl bg-surface rounded-modal shadow-card max-h-[90vh] overflow-y-auto" >
            <div className="p-xl border-b border-line flex justify-between items-center sticky top-0 bg-surface z-10" >
              <h2 className="text-xl font-bold text-content" >신규 지점 등록</h2>
              <button className="text-content-secondary hover:text-content" onClick={handleCloseAddBranch}>
                <X size={24}/>
              </button>
            </div>

            <div className="p-xl space-y-lg" >
              <FormSection title="기본 정보" columns={2}>
                {/* 지점명 */}
                <div className="space-y-xs" >
                  <label className="text-Label text-content-secondary" >지점명 <span className="text-state-error" >*</span></label>
                  <input
                    className={cn(
                      "w-full p-sm bg-surface-secondary rounded-input border focus:outline-none transition-colors",
                      formErrors.name ? "border-state-error focus:border-state-error" : "border-transparent focus:border-accent"
                    )}
                    placeholder="예: 스포짐 광화문점"
                    value={branchForm.name}
                    onChange={e => handleFormChange('name', e.target.value)}
                  />
                  {formErrors.name && (
                    <p className="flex items-center gap-xs text-Label text-state-error">
                      <AlertCircle size={12}/> {formErrors.name}
                    </p>
                  )}
                  <p className="text-Label text-content-secondary">2~30자 입력</p>
                </div>

                {/* 지점 코드 */}
                <div className="space-y-xs" >
                  <label className="text-Label text-content-secondary" >지점 코드 <span className="text-state-error" >*</span></label>
                  <div className="flex gap-xs" >
                    <input
                      className={cn(
                        "flex-1 p-sm bg-surface-secondary rounded-input border focus:outline-none transition-colors uppercase",
                        formErrors.code ? "border-state-error focus:border-state-error" : "border-transparent focus:border-accent",
                        codeAutoGenerated && "bg-accent-light/30"
                      )}
                      placeholder="예: SGJ"
                      value={branchForm.code}
                      maxLength={5}
                      onChange={e => handleFormChange('code', e.target.value.toUpperCase())}
                    />
                    <button
                      className="px-md py-sm bg-accent-light text-accent text-Label font-semibold rounded-button whitespace-nowrap hover:opacity-80 transition-opacity"
                      type="button"
                      onClick={handleAutoGenerateCode}
                    >
                      자동생성
                    </button>
                  </div>
                  {formErrors.code && (
                    <p className="flex items-center gap-xs text-Label text-state-error">
                      <AlertCircle size={12}/> {formErrors.code}
                    </p>
                  )}
                  <p className="text-Label text-content-secondary">영문 대문자 2~5자 (예: SGJ, SGKWH)</p>
                </div>

                {/* 대표 연락처 */}
                <div className="space-y-xs" >
                  <label className="text-Label text-content-secondary" >대표 연락처 <span className="text-state-error" >*</span></label>
                  <input
                    className={cn(
                      "w-full p-sm bg-surface-secondary rounded-input border focus:outline-none transition-colors",
                      formErrors.phone ? "border-state-error focus:border-state-error" : "border-transparent focus:border-accent"
                    )}
                    placeholder="02-000-0000"
                    value={branchForm.phone}
                    onChange={e => handleFormChange('phone', e.target.value)}
                  />
                  {formErrors.phone && (
                    <p className="flex items-center gap-xs text-Label text-state-error">
                      <AlertCircle size={12}/> {formErrors.phone}
                    </p>
                  )}
                </div>

                {/* 지점 관리자 */}
                <div className="space-y-xs" >
                  <label className="text-Label text-content-secondary" >지점 관리자 <span className="text-state-error" >*</span></label>
                  <select
                    className={cn(
                      "w-full p-sm bg-surface-secondary rounded-input border focus:outline-none transition-colors",
                      formErrors.managerId ? "border-state-error focus:border-state-error" : "border-transparent focus:border-accent"
                    )}
                    value={branchForm.managerId}
                    onChange={e => handleFormChange('managerId', e.target.value)}
                  >
                    <option value="">계정 선택</option>
                    <option value="owner1">김오너 (owner)</option>
                    <option value="owner2">박대표 (owner)</option>
                  </select>
                  {formErrors.managerId && (
                    <p className="flex items-center gap-xs text-Label text-state-error">
                      <AlertCircle size={12}/> {formErrors.managerId}
                    </p>
                  )}
                </div>
              </FormSection>

              <FormSection title="위치 및 운영 정보" columns={1}>
                <div className="space-y-xs" >
                  <label className="text-Label text-content-secondary" >주소 <span className="text-state-error" >*</span></label>
                  <div className="flex gap-xs" >
                    <input
                      className={cn(
                        "flex-1 p-sm bg-surface-secondary rounded-input border focus:outline-none transition-colors",
                        formErrors.address ? "border-state-error focus:border-state-error" : "border-transparent focus:border-accent"
                      )}
                      placeholder="주소를 검색하세요"
                      readOnly={true}
                      value={branchForm.address}
                    />
                    <button
                      className="px-md py-sm bg-surface-secondary text-content text-Label font-semibold rounded-button whitespace-nowrap hover:bg-surface-secondary transition-colors"
                      type="button"
                      onClick={() => {
                        // Mock 주소 설정
                        handleFormChange('address', '서울특별시 종로구 광화문광장 1');
                      }}
                    >
                      주소검색
                    </button>
                  </div>
                  {formErrors.address && (
                    <p className="flex items-center gap-xs text-Label text-state-error">
                      <AlertCircle size={12}/> {formErrors.address}
                    </p>
                  )}
                  <input
                    className="w-full mt-sm p-sm bg-surface-secondary rounded-input border border-transparent focus:border-accent focus:outline-none"
                    placeholder="상세 주소를 입력하세요"
                    value={branchForm.addressDetail}
                    onChange={e => handleFormChange('addressDetail', e.target.value)}
                  />
                </div>
                <div className="space-y-xs mt-md" >
                  <label className="text-Label text-content-secondary" >운영 시간 <span className="text-state-error" >*</span></label>
                  <div className="flex items-center gap-sm" >
                    <input
                      className="flex-1 p-sm bg-surface-secondary rounded-input border border-transparent focus:border-accent focus:outline-none"
                      type="time"
                      value={branchForm.openTime}
                      onChange={e => handleFormChange('openTime', e.target.value)}
                    />
                    <span className="text-content-secondary" >~</span>
                    <input
                      className="flex-1 p-sm bg-surface-secondary rounded-input border border-transparent focus:border-accent focus:outline-none"
                      type="time"
                      value={branchForm.closeTime}
                      onChange={e => handleFormChange('closeTime', e.target.value)}
                    />
                  </div>
                </div>
              </FormSection>

              <FormSection title="추가 설정" columns={1}>
                <div className="space-y-xs" >
                  <label className="text-Label text-content-secondary" >지점 로고</label>
                  <div className="border-2 border-dashed border-line rounded-xl p-xl flex flex-col items-center justify-center text-content-secondary hover:border-accent transition-colors cursor-pointer" >
                    <Plus size={32}/>
                    <span className="mt-sm text-sm" >이미지 업로드 (PNG, JPG)</span>
                  </div>
                </div>
                <div className="space-y-xs mt-md" >
                  <label className="text-Label text-content-secondary" >메모</label>
                  <textarea
                    className="w-full p-sm bg-surface-secondary rounded-input border border-transparent focus:border-accent focus:outline-none min-h-[80px]"
                    placeholder="지점 관련 특이사항을 입력하세요."
                    value={branchForm.memo}
                    onChange={e => handleFormChange('memo', e.target.value)}
                  />
                </div>
              </FormSection>
            </div>

            <div className="p-xl border-t border-line flex justify-end gap-sm sticky bottom-0 bg-surface" >
              <button className="px-lg py-sm text-content-secondary hover:bg-surface-secondary rounded-button transition-colors" onClick={handleCloseAddBranch}>취소</button>
              <button
                className="px-lg py-sm bg-primary text-white font-semibold rounded-button shadow-md hover:scale-[1.02] active:scale-[0.98] transition-all"
                onClick={handleAddBranchSubmit}
              >
                등록 완료
              </button>
            </div>
          </div>
        </div>
      )}

      {/* --- MODAL: 지점 이동 신청 --- */}
      {isMoveMemberOpen && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 backdrop-blur-sm p-md" >
          <div className="w-full max-w-lg bg-surface rounded-modal shadow-card" >
            <div className="p-xl border-b border-line flex justify-between items-center" >
              <h2 className="text-xl font-bold text-content" >회원 지점 이동 신청</h2>
              <button className="text-content-secondary hover:text-content" onClick={() => setIsMoveMemberOpen(false)}>
                <X size={24}/>
              </button>
            </div>

            <div className="p-xl space-y-lg" >
              <div className="space-y-xs" >
                <label className="text-Label text-content-secondary" >회원 검색 <span className="text-state-error" >*</span></label>
                <div className="relative" >
                  <Search className="absolute left-md top-1/2 -translate-y-1/2 text-content-secondary w-sm h-sm" />
                  <input className="w-full pl-xl pr-md py-sm bg-surface-secondary rounded-input border border-transparent focus:border-accent focus:outline-none" placeholder="회원명 또는 연락처 입력"/>
                </div>
              </div>

              <div className="grid grid-cols-2 gap-md" >
                <div className="space-y-xs" >
                  <label className="text-Label text-content-secondary" >현재 지점</label>
                  <input className="w-full p-sm bg-surface-secondary rounded-input border border-transparent text-content-secondary" value="스포짐 종각점" disabled={true}/>
                </div>
                <div className="space-y-xs" >
                  <label className="text-Label text-content-secondary" >이동할 지점 <span className="text-state-error" >*</span></label>
                  <select className="w-full p-sm bg-surface-secondary rounded-input border border-transparent focus:border-accent focus:outline-none" >
                    <option value="">지점 선택</option>
                    <option value="2">스포짐 강남점</option>
                    <option value="3">스포짐 여의도점</option>
                  </select>
                </div>
              </div>

              <div className="space-y-xs" >
                <label className="text-Label text-content-secondary" >이동일 <span className="text-state-error" >*</span></label>
                <input className="w-full p-sm bg-surface-secondary rounded-input border border-transparent focus:border-accent focus:outline-none" type="date" defaultValue="2026-02-19"/>
              </div>

              <div className="space-y-xs" >
                <label className="text-Label text-content-secondary" >이용권 처리 <span className="text-state-error" >*</span></label>
                <div className="flex gap-md mt-xs" >
                  <label className="flex items-center gap-xs cursor-pointer" >
                    <input className="accent-primary" type="radio" name="pass-action" defaultChecked={true}/>
                    <span className="text-sm" >기존 이용권 유지</span>
                  </label>
                  <label className="flex items-center gap-xs cursor-pointer" >
                    <input className="accent-primary" type="radio" name="pass-action"/>
                    <span className="text-sm" >신규 이용권 등록</span>
                  </label>
                </div>
              </div>

              <div className="space-y-xs" >
                <label className="text-Label text-content-secondary" >이동 사유</label>
                <textarea className="w-full p-sm bg-surface-secondary rounded-input border border-transparent focus:border-accent focus:outline-none min-h-[80px]" placeholder="이동 사유를 메모하세요."/>
              </div>
            </div>

            <div className="p-xl border-t border-line flex justify-end gap-sm" >
              <button className="px-lg py-sm text-content-secondary hover:bg-surface-secondary rounded-button transition-colors" onClick={() => setIsMoveMemberOpen(false)}>취소</button>
              <button className="px-lg py-sm bg-accent text-white font-semibold rounded-button shadow-md hover:scale-[1.02] active:scale-[0.98] transition-all" >신청 완료</button>
            </div>
          </div>
        </div>
      )}

      {/* --- MODAL: 지점 비활성화 (2단계) --- */}
      {isDeactivateOpen && deactivateTarget && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 backdrop-blur-sm p-md">
          <div className="w-full max-w-md bg-surface rounded-modal shadow-card">
            <div className="p-xl border-b border-line flex justify-between items-center">
              <h2 className="text-xl font-bold text-content flex items-center gap-sm">
                <AlertTriangle className="text-state-error" size={20}/>
                지점 비활성화
              </h2>
              <button className="text-content-secondary hover:text-content" onClick={() => setIsDeactivateOpen(false)}>
                <X size={24}/>
              </button>
            </div>

            <div className="p-xl space-y-lg">
              {deactivateStep === 1 ? (
                <>
                  {/* 1단계: 영향 범위 표시 */}
                  <div className="rounded-xl bg-state-error/5 border border-state-error/20 p-lg space-y-md">
                    <p className="text-base font-semibold text-content">
                      "{deactivateTarget.name}" 비활성화 시 영향 범위
                    </p>
                    <div className="grid grid-cols-2 gap-md">
                      <div className="bg-surface rounded-xl p-md text-center border border-line">
                        <p className="text-KPI-Large font-bold text-primary">
                          {deactivateTarget.members.toLocaleString()}명
                        </p>
                        <p className="text-Label text-content-secondary mt-xs">소속 회원</p>
                      </div>
                      <div className="bg-surface rounded-xl p-md text-center border border-line">
                        <p className="text-KPI-Large font-bold text-amber-600">
                          {deactivateTarget.activeContracts}건
                        </p>
                        <p className="text-Label text-content-secondary mt-xs">진행중 계약</p>
                      </div>
                    </div>
                    <div className="space-y-xs">
                      <p className="text-sm text-content-secondary flex items-start gap-xs">
                        <AlertCircle size={14} className="flex-shrink-0 mt-xs text-amber-600"/>
                        비활성화 시 해당 지점의 키오스크 및 앱 접근이 즉시 제한됩니다.
                      </p>
                      <p className="text-sm text-content-secondary flex items-start gap-xs">
                        <AlertCircle size={14} className="flex-shrink-0 mt-xs text-amber-600"/>
                        소속 회원 {deactivateTarget.members.toLocaleString()}명의 이용 내역이 일시 동결됩니다.
                      </p>
                      {deactivateTarget.activeContracts > 0 && (
                        <p className="text-sm text-state-error flex items-start gap-xs">
                          <AlertTriangle size={14} className="flex-shrink-0 mt-xs"/>
                          진행중인 계약 {deactivateTarget.activeContracts}건을 먼저 처리하는 것을 권장합니다.
                        </p>
                      )}
                    </div>
                  </div>
                  <div className="flex justify-end gap-sm">
                    <button
                      className="px-lg py-sm text-content-secondary hover:bg-surface-secondary rounded-button transition-colors"
                      onClick={() => setIsDeactivateOpen(false)}
                    >
                      취소
                    </button>
                    <button
                      className="px-lg py-sm bg-state-error text-white font-semibold rounded-button hover:opacity-90 transition-opacity"
                      onClick={handleDeactivateConfirm}
                    >
                      계속 진행
                    </button>
                  </div>
                </>
              ) : (
                <>
                  {/* 2단계: 최종 확인 */}
                  <div className="text-center space-y-md py-md">
                    <div className="w-[64px] h-[64px] bg-state-error/10 rounded-full flex items-center justify-center mx-auto">
                      <AlertTriangle className="text-state-error" size={32}/>
                    </div>
                    <p className="text-base font-semibold text-content">
                      정말로 비활성화하시겠습니까?
                    </p>
                    <p className="text-sm text-content-secondary">
                      <span className="font-semibold text-content">"{deactivateTarget.name}"</span>을(를) 비활성화합니다.
                      <br/>이 작업은 즉시 적용되며, 재활성화 전까지 해당 지점 서비스가 중단됩니다.
                    </p>
                  </div>
                  <div className="flex justify-end gap-sm">
                    <button
                      className="px-lg py-sm text-content-secondary hover:bg-surface-secondary rounded-button transition-colors"
                      onClick={() => setDeactivateStep(1)}
                    >
                      이전
                    </button>
                    <button
                      className="px-lg py-sm bg-state-error text-white font-semibold rounded-button hover:opacity-90 transition-opacity"
                      onClick={handleDeactivateConfirm}
                    >
                      최종 비활성화
                    </button>
                  </div>
                </>
              )}
            </div>
          </div>
        </div>
      )}
    </AppLayout>
  );
}
