'use client';
export const dynamic = 'force-dynamic';

﻿
import React, { useState, useEffect } from 'react';
import {
  Building2,
  Users,
  TrendingUp,
  Plus,
  ArrowLeftRight,
  MapPin,
  Phone,
  Calendar as CalendarIcon,
  MoreHorizontal,
  Download,
  BarChart3,
  PieChart,
  LineChart,
  Search,
  CheckCircle2,
  AlertCircle,
  X,
  ChevronRight,
  UserPlus,
  AlertTriangle
} from 'lucide-react';
import { cn } from '@/lib/utils';
import { moveToPage } from '@/internal';
import { toast } from 'sonner';

import AppLayout from "@/components/layout/AppLayout";
import PageHeader from "@/components/common/PageHeader";
import TabNav from "@/components/common/TabNav";
import StatCard from "@/components/common/StatCard";
import StatCardGrid from "@/components/common/StatCardGrid";
import { formatNumber } from "@/lib/format";
import DataTable from "@/components/common/DataTable";
import StatusBadge from "@/components/common/StatusBadge";
import SearchFilter from "@/components/common/SearchFilter";
import FormSection from "@/components/common/FormSection";
import ConfirmDialog from "@/components/ui/ConfirmDialog";
import Select from '@/components/ui/Select';
import Textarea from '@/components/ui/Textarea';
import Button from '@/components/ui/Button';
import { supabase } from '@/lib/supabase';
import { exportToExcel } from '@/lib/exportExcel';
import { useAuthStore } from '@/stores/authStore';

// 코드 중복 체크는 branches 상태에서 동적으로 처리

// --- 지점 등록 폼 타입 ---
interface BranchForm {
  name: string;
  code: string;
  phone: string;
  address: string;
  addressDetail: string;
  managerId: string;
  openTime: string;
  closeTime: string;
  maxCapacity: string;
  memo: string;
}

interface FormErrors {
  name?: string;
  code?: string;
  phone?: string;
  address?: string;
  managerId?: string;
}

const EMPTY_FORM: BranchForm = {
  name: '',
  code: '',
  phone: '',
  address: '',
  addressDetail: '',
  managerId: '',
  openTime: '06:00',
  closeTime: '23:30',
  maxCapacity: '',
  memo: '',
};

// 전화번호 포맷 검증
const isValidPhone = (v: string) => /^(0\d{1,2})-(\d{3,4})-(\d{4})$/.test(v);

// 지점 코드 검증: 영문 2~5자
const isValidCode = (v: string) => /^[A-Z]{2,5}$/.test(v);

// 지점명 검증: 2~30자
const isValidName = (v: string) => v.trim().length >= 2 && v.trim().length <= 30;

export default function BranchManagement() {
  const switchBranch = useAuthStore((s) => s.switchBranch);
  const [activeTab, setActiveTab] = useState('list');
  const [isAddBranchOpen, setIsAddBranchOpen] = useState(false);
  const [isMoveMemberOpen, setIsMoveMemberOpen] = useState(false);

  // 비활성화 관련 상태
  const [deactivateTarget, setDeactivateTarget] = useState<any>(null);
  const [deactivateStep, setDeactivateStep] = useState<1 | 2>(1); // 1: 영향 범위 확인, 2: 2차 확인
  const [isDeactivateOpen, setIsDeactivateOpen] = useState(false);
  const [isSaving, setIsSaving] = useState(false);

  // 상태 변경 관련 상태
  const [statusChangeTarget, setStatusChangeTarget] = useState<any>(null);
  const [statusChangeType, setStatusChangeType] = useState<'closed' | 'inactive' | null>(null);
  const [statusChangeInfo, setStatusChangeInfo] = useState<{ activeMembers: number; activeStaff: number } | null>(null);
  const [isStatusChangeOpen, setIsStatusChangeOpen] = useState(false);
  const [isStatusChangeSaving, setIsStatusChangeSaving] = useState(false);

  // 지점 등록 폼 상태
  const [branchForm, setBranchForm] = useState<BranchForm>(EMPTY_FORM);
  const [formErrors, setFormErrors] = useState<FormErrors>({});
  const [codeAutoGenerated, setCodeAutoGenerated] = useState(false);

  // Supabase 데이터 상태
  const [branches, setBranches] = useState<any[]>([]);
  const [integratedStats, setIntegratedStats] = useState<any[]>([]);

  const [movementHistory, setMovementHistory] = useState<any[]>([]);

  useEffect(() => {
    const fetchBranches = async () => {
      const { data, error } = await supabase
        .from('branches')
        .select('*');
      if (!error && data) {
        setBranches(data);

        // 지점별 회원 수, 매출 집계
        const stats = await Promise.all(data.map(async (b: any) => {
          const { count: memberCount } = await supabase
            .from('members')
            .select('*', { count: 'exact', head: true })
            .eq('branchId', b.id);

          const { data: salesData } = await supabase
            .from('sales')
            .select('amount')
            .eq('branchId', b.id);

          const totalSales = salesData?.reduce((sum: number, s: any) => sum + Number(s.amount || 0), 0) ?? 0;

          return {
            branch: b.name,
            members: memberCount ?? 0,
            sales: formatNumber(totalSales),
            attendance: '-',
          };
        }));
        setIntegratedStats(stats);
      }
    };
    fetchBranches();
  }, []);

  // --- 폼 검증 ---
  const validateForm = (): boolean => {
    const errors: FormErrors = {};

    if (!isValidName(branchForm.name)) {
      errors.name = '지점명은 2~30자로 입력해주세요.';
    }
    if (!branchForm.code.trim()) {
      errors.code = '지점 코드를 입력해주세요.';
    } else if (!isValidCode(branchForm.code)) {
      errors.code = '지점 코드는 영문 대문자 2~5자여야 합니다. (예: SGJ)';
    } else if (branches.some((b: any) => b.code === branchForm.code)) {
      errors.code = '이미 사용 중인 지점 코드입니다.';
    }
    if (!branchForm.phone.trim()) {
      errors.phone = '연락처를 입력해주세요.';
    } else if (!isValidPhone(branchForm.phone)) {
      errors.phone = '올바른 전화번호 형식으로 입력해주세요. (예: 02-000-0000)';
    }
    if (!branchForm.address.trim()) {
      errors.address = '주소를 입력해주세요.';
    }
    if (!branchForm.managerId) {
      errors.managerId = '지점 관리자를 선택해주세요.';
    }

    setFormErrors(errors);
    return Object.keys(errors).length === 0;
  };

  const handleAutoGenerateCode = () => {
    const nextNum = String(branches.length + 1).padStart(3, '0');
    const generated = `SG${nextNum}`;
    setBranchForm(f => ({ ...f, code: generated }));
    setCodeAutoGenerated(true);
    // 코드 에러 초기화
    setFormErrors(prev => ({ ...prev, code: undefined }));
  };

  const handleFormChange = (field: keyof BranchForm, value: string) => {
    setBranchForm(f => ({ ...f, [field]: value }));
    // 해당 필드 에러 초기화
    if (field in formErrors) {
      setFormErrors(prev => ({ ...prev, [field]: undefined }));
    }
    if (field === 'code') setCodeAutoGenerated(false);
  };

  const handleAddBranchSubmit = async () => {
    if (!validateForm()) return;
    // 중복 등록 방지
    if (isSaving) return;
    setIsSaving(true);

    try {
    const { data, error } = await supabase
      .from('branches')
      .insert({
        name: branchForm.name,
        code: branchForm.code,
        phone: branchForm.phone,
        address: branchForm.address + (branchForm.addressDetail ? ` ${branchForm.addressDetail}` : ''),
        status: 'active',
        regDate: new Date().toISOString().slice(0, 10),
      })
      .select()
      .single();

    if (error) {
      toast.error(`지점 등록 실패: ${error.message}`);
      return;
    }

    toast.success(`지점 "${branchForm.name}"이(가) 등록되었습니다.`);
    setBranches(prev => [...prev, data]);
    setIsAddBranchOpen(false);
    setBranchForm(EMPTY_FORM);
    setFormErrors({});
    } finally {
      setIsSaving(false);
    }
  };

  const handleCloseAddBranch = () => {
    setIsAddBranchOpen(false);
    setBranchForm(EMPTY_FORM);
    setFormErrors({});
    setCodeAutoGenerated(false);
  };

  // --- 비활성화 처리 ---
  const openDeactivate = (row: any) => {
    setDeactivateTarget(row);
    setDeactivateStep(1);
    setIsDeactivateOpen(true);
  };

  const handleDeactivateConfirm = () => {
    if (deactivateStep === 1) {
      setDeactivateStep(2);
    } else {
      toast.success(`"${deactivateTarget?.name}" 지점이 비활성화되었습니다.`);
      setIsDeactivateOpen(false);
      setDeactivateTarget(null);
    }
  };

  // --- 상태 변경 핸들러 ---
  const openStatusChange = async (row: any, type: 'closed' | 'inactive') => {
    setStatusChangeTarget(row);
    setStatusChangeType(type);

    if (type === 'closed') {
      // 활성 회원 수 조회
      const { count: activeMembers } = await supabase
        .from('members')
        .select('*', { count: 'exact', head: true })
        .eq('branchId', row.id)
        .eq('status', 'ACTIVE');

      // 재직 직원 수 조회
      const { count: activeStaff } = await supabase
        .from('staff')
        .select('*', { count: 'exact', head: true })
        .eq('branchId', row.id)
        .eq('isActive', true);

      setStatusChangeInfo({ activeMembers: activeMembers ?? 0, activeStaff: activeStaff ?? 0 });
    } else {
      setStatusChangeInfo(null);
    }

    setIsStatusChangeOpen(true);
  };

  const handleStatusChangeConfirm = async () => {
    if (!statusChangeTarget || !statusChangeType) return;
    if (isStatusChangeSaving) return;
    setIsStatusChangeSaving(true);

    try {
      const newStatus = statusChangeType === 'closed' ? 'closed' : 'inactive';
      const { error } = await supabase
        .from('branches')
        .update({ status: newStatus })
        .eq('id', statusChangeTarget.id);

      if (error) {
        toast.error(`상태 변경 실패: ${error.message}`);
        return;
      }

      setBranches(prev => prev.map(b => b.id === statusChangeTarget.id ? { ...b, status: newStatus } : b));
      const label = statusChangeType === 'closed' ? '폐점' : '임시휴업';
      toast.success(`"${statusChangeTarget.name}" 지점이 ${label} 처리되었습니다.`);
      setIsStatusChangeOpen(false);
      setStatusChangeTarget(null);
      setStatusChangeType(null);
      setStatusChangeInfo(null);
    } finally {
      setIsStatusChangeSaving(false);
    }
  };

  // --- Handlers ---
  const handleMoveMember = () => setIsMoveMemberOpen(true);

  // --- Table Columns ---
  const branchColumns = [
    { key: 'id', header: 'No', width: 60, align: 'center' as const },
    { key: 'name', header: '지점명', sortable: true, render: (v: string, row: any) => (
      <Button variant="ghost" size="sm" onClick={(e) => { e.stopPropagation(); switchBranch(String(row.id), v); toast.success(`${v} 지점으로 전환되었습니다`); }}>{v}</Button>
    ) },
    { key: 'code', header: '지점 코드', width: 120 },
    { key: 'address', header: '주소' },
    { key: 'phone', header: '연락처', width: 140 },
    { key: 'members', header: '회원 수', width: 100, align: 'right' as const, render: (v: number) => formatNumber(v ?? 0) },
    { key: 'staffs', header: '직원 수', width: 100, align: 'right' as const, render: (v: number) => formatNumber(v ?? 0) },
    {
      key: 'status',
      header: '상태',
      width: 120,
      align: 'center' as const,
      render: (v: string) => (
        <StatusBadge variant={v === 'active' || v === '운영중' ? 'success' : v === 'inactive' || v === '임시휴업' ? 'warning' : 'default'} dot={true} label={v === 'active' || v === '운영중' ? '운영중' : v === 'inactive' || v === '임시휴업' ? '임시휴업' : '폐점'}/>
      )
    },
    { key: 'regDate', header: '등록일', width: 120 },
    {
      key: 'actions',
      header: '메뉴',
      width: 200,
      align: 'center' as const,
      render: (_: any, row: any) => (
        <div className="flex items-center gap-xs" >
          <Button variant="ghost" size="sm" onClick={() => { toast.info(`${row.name} 관리 모드로 전환합니다.`); moveToPage(966); }}>관리</Button>
          <div className="w-[1px] h-3 bg-line" />
          <Button variant="ghost" size="sm">수정</Button>
          <div className="w-[1px] h-3 bg-line" />
          <Button variant="ghost" size="sm" onClick={() => openDeactivate(row)}>비활성</Button>
          <div className="w-[1px] h-3 bg-line" />
          <Select
            value=""
            onChange={(v) => {
              const val = v as 'closed' | 'inactive';
              if (val) openStatusChange(row, val);
            }}
            options={[
              { value: '', label: '상태변경', disabled: true },
              { value: 'inactive', label: '임시휴업' },
              { value: 'closed', label: '폐점' },
            ]}
          />
        </div>
      )
    }
  ];

  const historyColumns = [
    {
      key: 'memberName',
      header: '회원명',
      sortable: true,
      render: (v: string, row: any) => (
        <button
          className="text-primary hover:underline font-medium" onClick={() => moveToPage(985, { id: row.id })}>
          {v}
        </button>
      )
    },
    { key: 'from', header: '원 지점' },
    { key: 'to', header: '이동 지점' },
    { key: 'date', header: '이동일', sortable: true },
    { key: 'processor', header: '처리자' },
  ];

  const integratedColumns = [
    { key: 'branch', header: '지점명' },
    { key: 'members', header: '회원 수', align: 'right' as const, render: (v: number) => formatNumber(v ?? 0) },
    { key: 'sales', header: '매출액 (원)', align: 'right' as const },
    { key: 'attendance', header: '평균 출석률', align: 'right' as const },
  ];

  return (
    <AppLayout >
      <PageHeader title="지점 관리 (멀티지점)" description="전체 지점의 운영 현황을 통합 관리하고 지점 간 데이터 이동을 처리합니다." actions={
          <div className="flex gap-sm">
            <button
              className="flex items-center gap-xs px-md py-sm bg-primary-light text-primary hover:bg-primary hover:text-white transition-all rounded-button text-Label font-semibold"
              onClick={handleMoveMember}
            >
              <ArrowLeftRight size={16} />
              지점 이동 신청
            </button>
            <button
              className="flex items-center gap-xs px-md py-sm bg-primary text-white hover:opacity-90 transition-all rounded-button text-Label font-semibold"
              onClick={() => setIsAddBranchOpen(true)}
            >
              <Plus size={16} />
              신규 지점 등록
            </button>
          </div>
        }/>

      <TabNav
        className="mb-lg" tabs={[
          { key: 'list', label: '지점 목록', icon: Building2 },
          { key: 'integrated', label: '통합 현황', icon: BarChart3 },
          { key: 'history', label: '지점 간 이동', icon: ArrowLeftRight },
        ]} activeTab={activeTab} onTabChange={setActiveTab}/>

      {/* --- TAB: 지점 목록 --- */}
      {activeTab === 'list' && (
        <div className="space-y-lg animate-in fade-in duration-300" >
          <StatCardGrid cols={4}>
            <StatCard label="총 지점 수" value={`${branches.length}개`} icon={<Building2 />} variant="default"/>
            <StatCard label="총 회원 수" value={`${formatNumber(integratedStats.reduce((s, i) => s + (i.members ?? 0), 0))}명`} icon={<Users />} variant="mint"/>
            <StatCard label="이번 달 매출" value={`${formatNumber(integratedStats.reduce((s, i) => s + Number(String(i.sales).replace(/,/g, '') || 0), 0))}원`} icon={<TrendingUp />} variant="peach"/>
            <StatCard label="활성 지점" value={`${branches.filter((b: any) => b.status === 'active' || b.status === '운영중').length}개`} icon={<CheckCircle2 />} description={`${branches.filter((b: any) => b.status !== 'active' && b.status !== '운영중').length}개 비활성`} variant="default"/>
          </StatCardGrid>

          <SearchFilter searchPlaceholder="지점명 또는 주소 검색" filters={[
              {
                key: 'status',
                label: '상태',
                type: 'select',
                options: [
                  { value: 'active', label: '운영중' },
                  { value: 'inactive', label: '임시휴업' },
                  { value: 'closed', label: '폐점' }
                ]
              }
            ]}/>

          <DataTable title="지점 현황 목록" columns={branchColumns} data={branches} onDownloadExcel={() => {
            const exportColumns = [
              { key: 'id', header: 'No' },
              { key: 'name', header: '지점명' },
              { key: 'code', header: '지점 코드' },
              { key: 'address', header: '주소' },
              { key: 'phone', header: '연락처' },
              { key: 'members', header: '회원 수' },
              { key: 'staffs', header: '직원 수' },
              { key: 'status', header: '상태' },
              { key: 'regDate', header: '등록일' },
            ];
            exportToExcel(branches as Record<string, unknown>[], exportColumns, { filename: '지점목록' });
            toast.success(`${branches.length}건 엑셀 다운로드 완료`);
          }}/>
        </div>
      )}

      {/* --- TAB: 통합 현황 --- */}
      {activeTab === 'integrated' && (
        <div className="space-y-lg animate-in fade-in duration-300" >
          <div className="flex justify-between items-center" >
            <div className="flex items-center gap-sm p-sm bg-surface rounded-xl border border-line shadow-card" >
              <button className="px-md py-xs bg-primary-light text-primary rounded-button text-Label font-semibold" >월간</button>
              <button className="px-md py-xs text-content-secondary hover:text-content rounded-button text-Label" >주간</button>
              <button className="px-md py-xs text-content-secondary hover:text-content rounded-button text-Label" >연간</button>
            </div>
            <p className="text-sm text-content-secondary" >기준: 2026.02.01 ~ 2026.02.19</p>
          </div>

          <div className="grid grid-cols-1 lg:grid-cols-3 gap-md" >
            <div className="lg:col-span-2 p-lg bg-surface rounded-xl border border-line shadow-card" >
              <div className="flex items-center justify-between mb-lg" >
                <h3 className="text-xl font-bold text-content flex items-center gap-xs" >
                  <BarChart3 className="text-primary" size={20}/>
                  지점별 매출 비교
                </h3>
              </div>
              <div className="space-y-lg" >
                {integratedStats.map((item, idx) => (
                  <div className="space-y-xs" key={idx}>
                    <div className="flex justify-between text-sm" >
                      <span className="font-medium text-content" >{item.branch}</span>
                      <span className="text-content-secondary" >{item.sales}원</span>
                    </div>
                    <div className="h-2 w-full bg-surface-secondary rounded-full overflow-hidden" >
                      <div
                        className="h-full bg-primary rounded-full" style={{ width: `${(parseInt(item.sales.replace(/,/g, '')) / 80000000) * 100}%` }}/>
                    </div>
                  </div>
                ))}
              </div>
            </div>

            <div className="p-lg bg-surface rounded-xl border border-line shadow-card" >
              <h3 className="text-xl font-bold text-content flex items-center gap-xs mb-lg" >
                <PieChart className="text-accent" size={20}/>
                지점별 회원 현황
              </h3>
              <div className="flex flex-col items-center justify-center h-[240px]" >
                <div className="relative w-40 h-40 rounded-full border-[12px] border-surface-secondary flex items-center justify-center" >
                  <div className="absolute inset-[-12px] rounded-full border-[12px] border-primary border-r-transparent border-b-transparent border-l-transparent rotate-[45deg]" />
                  <div className="absolute inset-[-12px] rounded-full border-[12px] border-accent border-t-transparent border-b-transparent border-l-transparent rotate-[-30deg]" />
                  <div className="text-center" >
                    <p className="text-Label text-content-secondary" >전체 회원</p>
                    <p className="text-xl font-bold text-content">{formatNumber(integratedStats.reduce((s, i) => s + (i.members ?? 0), 0))}</p>
                  </div>
                </div>
                <div className="mt-lg grid grid-cols-2 gap-sm w-full" >
                  {(() => {
                    const totalMembers = integratedStats.reduce((s, i) => s + (i.members ?? 0), 0);
                    const colors = ['bg-primary', 'bg-accent', 'bg-information', 'bg-state-warning', 'bg-state-error'];
                    return integratedStats.map((item, idx) => (
                      <div className="flex items-center gap-xs" key={idx}>
                        <div className={`w-2 h-2 rounded-full ${colors[idx % colors.length]}`} />
                        <span className="text-Label text-content-secondary">
                          {item.branch} ({totalMembers > 0 ? Math.round((item.members / totalMembers) * 100) : 0}%)
                        </span>
                      </div>
                    ));
                  })()}
                </div>
              </div>
            </div>
          </div>

          <DataTable title="지점별 상세 통합 통계" columns={integratedColumns} data={integratedStats} onDownloadExcel={() => {
            const exportColumns = [
              { key: 'branch', header: '지점명' },
              { key: 'members', header: '회원 수' },
              { key: 'sales', header: '매출액 (원)' },
              { key: 'attendance', header: '평균 출석률' },
            ];
            exportToExcel(integratedStats as Record<string, unknown>[], exportColumns, { filename: '지점통합통계' });
            toast.success(`${integratedStats.length}건 엑셀 다운로드 완료`);
          }}/>
        </div>
      )}

      {/* --- TAB: 지점 간 이동 --- */}
      {activeTab === 'history' && (
        <div className="space-y-lg animate-in fade-in duration-300" >
          <StatCardGrid cols={3}>
            <StatCard label="이달의 지점 이동" value="12건" icon={<ArrowLeftRight />} variant="default"/>
            <StatCard label="주요 유입 지점" value="강남점" icon={<UserPlus />} description="최근 30일 기준" variant="mint"/>
            <StatCard label="주요 유출 지점" value="여의도점" icon={<X size={24} />} description="거주지 이전 사유 80%" variant="default"/>
          </StatCardGrid>

          <SearchFilter searchPlaceholder="회원명 검색" filters={[
              {
                key: 'dateRange',
                label: '조회 기간',
                type: 'dateRange'
              },
              {
                key: 'fromBranch',
                label: '출발 지점',
                type: 'select',
                options: branches.map(b => ({ value: b.name, label: b.name }))
              }
            ]}/>

          <DataTable title="회원 지점 이동 이력" columns={historyColumns} data={movementHistory}/>
        </div>
      )}

      {/* --- MODAL: 신규 지점 등록 (검증 포함) --- */}
      {isAddBranchOpen && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 backdrop-blur-sm p-md" >
          <div className="w-full max-w-2xl bg-surface rounded-modal shadow-card max-h-[90vh] overflow-y-auto" >
            <div className="p-xl border-b border-line flex justify-between items-center sticky top-0 bg-surface z-10" >
              <h2 className="text-xl font-bold text-content" >신규 지점 등록</h2>
              <Button variant="ghost" size="sm" icon={<X size={24}/>} onClick={handleCloseAddBranch} />
            </div>

            <div className="p-xl space-y-lg" >
              <FormSection title="기본 정보" columns={2}>
                {/* 지점명 */}
                <div className="space-y-xs" >
                  <label className="text-Label text-content-secondary" >지점명 <span className="text-state-error" >*</span></label>
                  <input
                    className={cn(
                      "w-full p-sm bg-surface-secondary rounded-input border focus:outline-none transition-colors",
                      formErrors.name ? "border-state-error focus:border-state-error" : "border-transparent focus:border-accent"
                    )}
                    placeholder="예: FitGenie CRM 광화문점"
                    value={branchForm.name}
                    onChange={e => handleFormChange('name', e.target.value)}
                  />
                  {formErrors.name && (
                    <p className="flex items-center gap-xs text-Label text-state-error">
                      <AlertCircle size={12}/> {formErrors.name}
                    </p>
                  )}
                  <p className="text-Label text-content-secondary">2~30자 입력</p>
                </div>

                {/* 지점 코드 */}
                <div className="space-y-xs" >
                  <label className="text-Label text-content-secondary" >지점 코드 <span className="text-state-error" >*</span></label>
                  <div className="flex gap-xs" >
                    <input
                      className={cn(
                        "flex-1 p-sm bg-surface-secondary rounded-input border focus:outline-none transition-colors uppercase",
                        formErrors.code ? "border-state-error focus:border-state-error" : "border-transparent focus:border-accent",
                        codeAutoGenerated && "bg-accent-light/30"
                      )}
                      placeholder="예: SGJ"
                      value={branchForm.code}
                      maxLength={5}
                      onChange={e => handleFormChange('code', e.target.value.toUpperCase())}
                    />
                    <button
                      className="px-md py-sm bg-accent-light text-accent text-Label font-semibold rounded-button whitespace-nowrap hover:opacity-80 transition-opacity"
                      type="button"
                      onClick={handleAutoGenerateCode}
                    >
                      자동생성
                    </button>
                  </div>
                  {formErrors.code && (
                    <p className="flex items-center gap-xs text-Label text-state-error">
                      <AlertCircle size={12}/> {formErrors.code}
                    </p>
                  )}
                  <p className="text-Label text-content-secondary">영문 대문자 2~5자 (예: SGJ, SGKWH)</p>
                </div>

                {/* 대표 연락처 */}
                <div className="space-y-xs" >
                  <label className="text-Label text-content-secondary" >대표 연락처 <span className="text-state-error" >*</span></label>
                  <input
                    className={cn(
                      "w-full p-sm bg-surface-secondary rounded-input border focus:outline-none transition-colors",
                      formErrors.phone ? "border-state-error focus:border-state-error" : "border-transparent focus:border-accent"
                    )}
                    placeholder="02-000-0000"
                    value={branchForm.phone}
                    onChange={e => handleFormChange('phone', e.target.value)}
                  />
                  {formErrors.phone && (
                    <p className="flex items-center gap-xs text-Label text-state-error">
                      <AlertCircle size={12}/> {formErrors.phone}
                    </p>
                  )}
                </div>

                {/* 지점 관리자 */}
                <div className="space-y-xs" >
                  <label className="text-Label text-content-secondary" >지점 관리자 <span className="text-state-error" >*</span></label>
                  <Select
                    className={cn(
                      "w-full p-sm bg-surface-secondary rounded-input border focus:outline-none transition-colors",
                      formErrors.managerId ? "border-state-error focus:border-state-error" : "border-transparent focus:border-accent"
                    )}
                    value={branchForm.managerId}
                    onChange={(v) => handleFormChange('managerId', v)}
                    options={[
                      { value: '', label: '계정 선택' },
                      { value: 'owner1', label: '김오너 (owner)' },
                      { value: 'owner2', label: '박대표 (owner)' },
                    ]}
                  />
                  {formErrors.managerId && (
                    <p className="flex items-center gap-xs text-Label text-state-error">
                      <AlertCircle size={12}/> {formErrors.managerId}
                    </p>
                  )}
                </div>
              </FormSection>

              <FormSection title="위치 및 운영 정보" columns={1}>
                <div className="space-y-xs" >
                  <label className="text-Label text-content-secondary" >주소 <span className="text-state-error" >*</span></label>
                  <div className="flex gap-xs" >
                    <input
                      className={cn(
                        "flex-1 p-sm bg-surface-secondary rounded-input border focus:outline-none transition-colors",
                        formErrors.address ? "border-state-error focus:border-state-error" : "border-transparent focus:border-accent"
                      )}
                      placeholder="주소를 검색하세요"
                      readOnly={true}
                      value={branchForm.address}
                    />
                    <button
                      className="px-md py-sm bg-surface-secondary text-content text-Label font-semibold rounded-button whitespace-nowrap hover:bg-surface-secondary transition-colors"
                      type="button"
                      onClick={() => {
                        // Mock 주소 설정
                        handleFormChange('address', '서울특별시 종로구 광화문광장 1');
                      }}
                    >
                      주소검색
                    </button>
                  </div>
                  {formErrors.address && (
                    <p className="flex items-center gap-xs text-Label text-state-error">
                      <AlertCircle size={12}/> {formErrors.address}
                    </p>
                  )}
                  <input
                    className="w-full mt-sm p-sm bg-surface-secondary rounded-input border border-transparent focus:border-accent focus:outline-none"
                    placeholder="상세 주소를 입력하세요"
                    value={branchForm.addressDetail}
                    onChange={e => handleFormChange('addressDetail', e.target.value)}
                  />
                </div>
                <div className="space-y-xs mt-md" >
                  <label className="text-Label text-content-secondary" >운영 시간 <span className="text-state-error" >*</span></label>
                  <div className="flex items-center gap-sm" >
                    <input
                      className="flex-1 p-sm bg-surface-secondary rounded-input border border-transparent focus:border-accent focus:outline-none"
                      type="time"
                      value={branchForm.openTime}
                      onChange={e => handleFormChange('openTime', e.target.value)}
                    />
                    <span className="text-content-secondary" >~</span>
                    <input
                      className="flex-1 p-sm bg-surface-secondary rounded-input border border-transparent focus:border-accent focus:outline-none"
                      type="time"
                      value={branchForm.closeTime}
                      onChange={e => handleFormChange('closeTime', e.target.value)}
                    />
                  </div>
                </div>
                {/* 최대 정원 */}
                <div className="space-y-xs">
                  <label className="text-Label text-content-secondary">최대 정원</label>
                  <input
                    className="w-full p-sm bg-surface-secondary rounded-input border border-transparent focus:border-accent focus:outline-none"
                    type="number"
                    placeholder="동시 수용 가능 인원"
                    value={branchForm.maxCapacity}
                    onChange={e => handleFormChange('maxCapacity', e.target.value)}
                  />
                </div>
              </FormSection>

              <FormSection title="추가 설정" columns={1}>
                <div className="space-y-xs" >
                  <label className="text-Label text-content-secondary" >지점 로고</label>
                  <div className="border-2 border-dashed border-line rounded-xl p-xl flex flex-col items-center justify-center text-content-secondary hover:border-accent transition-colors cursor-pointer" >
                    <Plus size={32}/>
                    <span className="mt-sm text-sm" >이미지 업로드 (PNG, JPG)</span>
                  </div>
                </div>
                <div className="space-y-xs mt-md" >
                  <label className="text-Label text-content-secondary" >메모</label>
                  <Textarea
                    className="w-full p-sm bg-surface-secondary rounded-input border border-transparent focus:border-accent focus:outline-none min-h-[80px]"
                    placeholder="지점 관련 특이사항을 입력하세요."
                    value={branchForm.memo}
                    onChange={e => handleFormChange('memo', e.target.value)}
                  />
                </div>
              </FormSection>
            </div>

            <div className="p-xl border-t border-line flex justify-end gap-sm sticky bottom-0 bg-surface" >
              <Button variant="outline" onClick={handleCloseAddBranch}>취소</Button>
              <Button variant="primary" onClick={handleAddBranchSubmit} disabled={isSaving} loading={isSaving}>등록 완료</Button>
            </div>
          </div>
        </div>
      )}

      {/* --- MODAL: 지점 이동 신청 --- */}
      {isMoveMemberOpen && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 backdrop-blur-sm p-md" >
          <div className="w-full max-w-lg bg-surface rounded-modal shadow-card" >
            <div className="p-xl border-b border-line flex justify-between items-center" >
              <h2 className="text-xl font-bold text-content" >회원 지점 이동 신청</h2>
              <Button variant="ghost" size="sm" icon={<X size={24}/>} onClick={() => setIsMoveMemberOpen(false)} />
            </div>

            <div className="p-xl space-y-lg" >
              <div className="space-y-xs" >
                <label className="text-Label text-content-secondary" >회원 검색 <span className="text-state-error" >*</span></label>
                <div className="relative" >
                  <Search className="absolute left-md top-1/2 -translate-y-1/2 text-content-secondary w-sm h-sm" />
                  <input className="w-full pl-xl pr-md py-sm bg-surface-secondary rounded-input border border-transparent focus:border-accent focus:outline-none" placeholder="회원명 또는 연락처 입력"/>
                </div>
              </div>

              <div className="grid grid-cols-2 gap-md" >
                <div className="space-y-xs" >
                  <label className="text-Label text-content-secondary" >현재 지점</label>
                  <input className="w-full p-sm bg-surface-secondary rounded-input border border-transparent text-content-secondary" value="FitGenie CRM 종각점" disabled={true}/>
                </div>
                <div className="space-y-xs" >
                  <label className="text-Label text-content-secondary" >이동할 지점 <span className="text-state-error" >*</span></label>
                  <Select
                    options={[
                      { value: '', label: '지점 선택' },
                      { value: '2', label: 'FitGenie CRM 강남점' },
                      { value: '3', label: 'FitGenie CRM 여의도점' },
                    ]}
                  />
                </div>
              </div>

              <div className="space-y-xs" >
                <label className="text-Label text-content-secondary" >이동일 <span className="text-state-error" >*</span></label>
                <input className="w-full p-sm bg-surface-secondary rounded-input border border-transparent focus:border-accent focus:outline-none" type="date" defaultValue={new Date().toISOString().slice(0, 10)}/>
              </div>

              <div className="space-y-xs" >
                <label className="text-Label text-content-secondary" >이용권 처리 <span className="text-state-error" >*</span></label>
                <div className="flex gap-md mt-xs" >
                  <label className="flex items-center gap-xs cursor-pointer" >
                    <input className="accent-primary" type="radio" name="pass-action" defaultChecked={true}/>
                    <span className="text-sm" >기존 이용권 유지</span>
                  </label>
                  <label className="flex items-center gap-xs cursor-pointer" >
                    <input className="accent-primary" type="radio" name="pass-action"/>
                    <span className="text-sm" >신규 이용권 등록</span>
                  </label>
                </div>
              </div>

              <div className="space-y-xs" >
                <label className="text-Label text-content-secondary" >이동 사유</label>
                <Textarea className="w-full p-sm bg-surface-secondary rounded-input border border-transparent focus:border-accent focus:outline-none min-h-[80px]" placeholder="이동 사유를 메모하세요."/>
              </div>
            </div>

            <div className="p-xl border-t border-line flex justify-end gap-sm" >
              <Button variant="outline" onClick={() => setIsMoveMemberOpen(false)}>취소</Button>
              <Button variant="primary">신청 완료</Button>
            </div>
          </div>
        </div>
      )}

      {/* --- MODAL: 지점 비활성화 (2단계) --- */}
      {isDeactivateOpen && deactivateTarget && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 backdrop-blur-sm p-md">
          <div className="w-full max-w-md bg-surface rounded-modal shadow-card">
            <div className="p-xl border-b border-line flex justify-between items-center">
              <h2 className="text-xl font-bold text-content flex items-center gap-sm">
                <AlertTriangle className="text-state-error" size={20}/>
                지점 비활성화
              </h2>
              <Button variant="ghost" size="sm" icon={<X size={24}/>} onClick={() => setIsDeactivateOpen(false)} />
            </div>

            <div className="p-xl space-y-lg">
              {deactivateStep === 1 ? (
                <>
                  {/* 1단계: 영향 범위 표시 */}
                  <div className="rounded-xl bg-state-error/5 border border-state-error/20 p-lg space-y-md">
                    <p className="text-base font-semibold text-content">
                      "{deactivateTarget.name}" 비활성화 시 영향 범위
                    </p>
                    <div className="grid grid-cols-2 gap-md">
                      <div className="bg-surface rounded-xl p-md text-center border border-line">
                        <p className="text-KPI-Large font-bold text-primary">
                          {formatNumber(deactivateTarget.members ?? 0)}명
                        </p>
                        <p className="text-Label text-content-secondary mt-xs">소속 회원</p>
                      </div>
                      <div className="bg-surface rounded-xl p-md text-center border border-line">
                        <p className="text-KPI-Large font-bold text-amber-600">
                          {deactivateTarget.activeContracts}건
                        </p>
                        <p className="text-Label text-content-secondary mt-xs">진행중 계약</p>
                      </div>
                    </div>
                    <div className="space-y-xs">
                      <p className="text-sm text-content-secondary flex items-start gap-xs">
                        <AlertCircle size={14} className="flex-shrink-0 mt-xs text-amber-600"/>
                        비활성화 시 해당 지점의 키오스크 및 앱 접근이 즉시 제한됩니다.
                      </p>
                      <p className="text-sm text-content-secondary flex items-start gap-xs">
                        <AlertCircle size={14} className="flex-shrink-0 mt-xs text-amber-600"/>
                        소속 회원 {formatNumber(deactivateTarget.members ?? 0)}명의 이용 내역이 일시 동결됩니다.
                      </p>
                      {deactivateTarget.activeContracts > 0 && (
                        <p className="text-sm text-state-error flex items-start gap-xs">
                          <AlertTriangle size={14} className="flex-shrink-0 mt-xs"/>
                          진행중인 계약 {deactivateTarget.activeContracts}건을 먼저 처리하는 것을 권장합니다.
                        </p>
                      )}
                    </div>
                  </div>
                  <div className="flex justify-end gap-sm">
                    <Button variant="outline" onClick={() => setIsDeactivateOpen(false)}>취소</Button>
                    <Button variant="danger" onClick={handleDeactivateConfirm}>계속 진행</Button>
                  </div>
                </>
              ) : (
                <>
                  {/* 2단계: 최종 확인 */}
                  <div className="text-center space-y-md py-md">
                    <div className="w-[64px] h-[64px] bg-state-error/10 rounded-full flex items-center justify-center mx-auto">
                      <AlertTriangle className="text-state-error" size={32}/>
                    </div>
                    <p className="text-base font-semibold text-content">
                      정말로 비활성화하시겠습니까?
                    </p>
                    <p className="text-sm text-content-secondary">
                      <span className="font-semibold text-content">"{deactivateTarget.name}"</span>을(를) 비활성화합니다.
                      <br/>이 작업은 즉시 적용되며, 재활성화 전까지 해당 지점 서비스가 중단됩니다.
                    </p>
                  </div>
                  <div className="flex justify-end gap-sm">
                    <Button variant="outline" onClick={() => setDeactivateStep(1)}>이전</Button>
                    <Button variant="danger" onClick={handleDeactivateConfirm}>최종 비활성화</Button>
                  </div>
                </>
              )}
            </div>
          </div>
        </div>
      )}
      {/* --- MODAL: 상태 변경 경고 다이얼로그 --- */}
      {isStatusChangeOpen && statusChangeTarget && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 backdrop-blur-sm p-md">
          <div className="w-full max-w-md bg-surface rounded-modal shadow-card">
            <div className="p-xl border-b border-line flex justify-between items-center">
              <h2 className="text-xl font-bold text-content flex items-center gap-sm">
                <AlertTriangle className="text-state-error" size={20}/>
                {statusChangeType === 'closed' ? '폐점 처리' : '임시휴업 처리'}
              </h2>
              <Button variant="ghost" size="sm" icon={<X size={24}/>} onClick={() => setIsStatusChangeOpen(false)} />
            </div>

            <div className="p-xl space-y-lg">
              {statusChangeType === 'closed' && statusChangeInfo ? (
                <>
                  <div className="rounded-xl bg-state-error/5 border border-state-error/20 p-lg space-y-md">
                    <p className="text-base font-semibold text-content">
                      "{statusChangeTarget.name}" 지점의 현황
                    </p>
                    <div className="grid grid-cols-2 gap-md">
                      <div className="bg-surface rounded-xl p-md text-center border border-line">
                        <p className="text-KPI-Large font-bold text-primary">
                          {formatNumber(statusChangeInfo.activeMembers)}명
                        </p>
                        <p className="text-Label text-content-secondary mt-xs">활성 회원</p>
                      </div>
                      <div className="bg-surface rounded-xl p-md text-center border border-line">
                        <p className="text-KPI-Large font-bold text-amber-600">
                          {formatNumber(statusChangeInfo.activeStaff)}명
                        </p>
                        <p className="text-Label text-content-secondary mt-xs">재직 직원</p>
                      </div>
                    </div>
                    <p className="text-sm text-content-secondary flex items-start gap-xs">
                      <AlertCircle size={14} className="flex-shrink-0 mt-xs text-state-error"/>
                      이 지점에 활성 회원 {statusChangeInfo.activeMembers}명, 재직 직원 {statusChangeInfo.activeStaff}명이 있습니다. 폐점 처리하시겠습니까?
                    </p>
                  </div>
                </>
              ) : (
                <div className="py-md">
                  <p className="text-base text-content">
                    <span className="font-semibold">"{statusChangeTarget.name}"</span> 지점을 임시휴업으로 변경하시겠습니까?
                  </p>
                  <p className="text-sm text-content-secondary mt-sm">
                    임시휴업 상태에서는 해당 지점의 신규 등록이 제한됩니다.
                  </p>
                </div>
              )}

              <div className="flex justify-end gap-sm">
                <Button variant="outline" onClick={() => setIsStatusChangeOpen(false)}>취소</Button>
                <Button variant="danger" onClick={handleStatusChangeConfirm} disabled={isStatusChangeSaving} loading={isStatusChangeSaving}>
                  {statusChangeType === 'closed' ? '폐점 확인' : '임시휴업 확인'}
                </Button>
              </div>
            </div>
          </div>
        </div>
      )}
    </AppLayout>
  );
}

